  
baseURL: https://blog.shaokunxie.com
languageCode: en-us
title: Shaokun Xie's Notebook

pagination:
  pagerSize: 10
assetDir: ./static

enableEmoji: true
hasCJKLanguage: true
permalinks:
  posts: /posts/:title/


markup:
  highlight:
    guessSyntax: true
    style: emacs
  goldmark:
    renderer:
      unsafe: true


social:
  github: https://github.com/Shaokun-X


params:
  author: Shaokun XIE
  # bio: Software Engineer
  description: Write down things that I have forgotten at least twice or that have annoyed me a lot :)
  enableRSS: true
  # enableComments: true
